// user-actions
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// lobby-actions
export const CREATE_LOBBY = 'CREATE_LOBBY';
export const CREATE_LOBBY_SUCCESS = 'CREATE_LOBBY_SUCCESS';
export const CREATE_LOBBY_FAILURE = 'CREATE_LOBBY_FAILURE';

export const ACCEPT_INVITE = 'ACCEPT_INVITE';
export const ACCEPT_INVITE_SUCCESS = 'ACCEPT_INVITE_SUCCESS';
export const ACCEPT_INVITE_FAILURE = 'ACCEPT_INVITE_FAILURE';

export const DECLINE_INVITE = 'DECLINE_INVITE';
export const DECLINE_INVITE_SUCCESS = 'DECLINE_INVITE_SUCCESS';
export const DECLINE_INVITE_FAILURE = 'DECLINE_INVITE_FAILURE';

export const INVITE_PLAYER = 'INVITE_PLAYER';
export const INVITE_PLAYER_SUCCESS = 'INVITE_PLAYER_SUCCESS';
export const INVITE_PLAYER_FAILURE = 'INVITE_PLAYER_FAILURE';
