// user-actions
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// lobby-actions
export const CREATE_LOBBY = 'CREATE_LOBBY';
export const CREATE_LOBBY_SUCCESS = 'CREATE_LOBBY_SUCCESS';
export const CREATE_LOBBY_FAILURE = 'CREATE_LOBBY_FAILURE';
